### ISSUE TITLE
Compilation fails on archlinux

### ISSUE THREAD

**Issue by Origin-yy** [spcl/rFaaS#20]
I used the code of the latest master branch and tried to compile it on my computer, but there was a problem of spdlog dependency. You can see that the version of spdlog installed by my archlinux package manager does not match the code of the current branch. We should use gitmodule to introduce into the current project instead of relying on the system's own.
I'm willing to submit a PR for this.

OS : ArchLinux 6.2.2
spdlog version : 1.11.0-2

**Comment by mcopik** [comment]
@Origin-yy Thank you so much! Yes, at the moment, we try to use an existing `spdlog` installation when possible to speed up builds and simplify deployments. When unavailable, [we pull the spdlog and install version v1.8](https://github.com/spcl/rFaaS/blob/master/cmake/dependencies.cmake#L23).

We should either add a CMake option to enforce using the custom version. Even better, we could call `find_package` with a specific version, or check the version of the already installed copy and decide if we can use it. Not sure if `spdlog` exports it correctly.

Please let me know if you have any questions or need an instance - I'm happy to help.
